USE `trash-userdb`;

INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu procrastines si fort que même ta To-Do List t''a ghosté.', 0, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T''as repoussé l''échec... pour mieux t''y écraser demain.', 0, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T''as remis "reprendre ta vie en main" à la semaine prochaine. Pour la 7e fois.', 1, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('À ce rythme, même ton réveil a abandonné l''idée de t''aider.', 1, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu fais rien, mais tu culpabilises à fond. Un vrai sportif de la flemme.', 2, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T''as atteint le niveau où "penser à commencer" te fatigue déjà.', 2, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu avances... dans ta tête. Dans la vraie vie ? On attend toujours.', 3, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Ton plus gros projet en cours, c''est d''éviter les projets.', 3, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu procrastines, mais avec un peu de style. Presque artistique.', 4, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as ouvert le fichier. C’est un début. Lointain, mais un début.', 4, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’es dans cet entre-deux étrange : pas assez motivé, pas assez écroulé.', 5, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Ni fait, ni à faire. Mais t’as réfléchi à faire. C’est déjà trop.', 5, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T''as coché une tâche aujourd''hui. Ou t''as juste changé de couleur sur ton Notion ?', 6, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu repousses des trucs, mais moins violemment qu’avant. C’est presque du progrès.', 6, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as réussi à faire quelque chose aujourd’hui. Et sans t’auto-humilier ? Respect.', 7, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu procrastines encore, mais maintenant c’est stratégique. Genre… t’y crois.', 7, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu fais les choses. Dans les temps. T’es qui et qu’as-tu fait de l’ancien toi ?', 8, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu domines ta to-do comme un patron. Les excuses pleurent dans un coin.', 8, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Procrastination ? Jamais entendu. C’est un mot de pauvres.', 9, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’es à ça de devenir un mythe de productivité. Une légende urbaine.', 9, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu fais les choses avant même qu’on te les demande. T’es devenu une menace pour les fainéants.', 10, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu viens littéralement d’éteindre le concept de procrastination. Il te salue.', 10, 1);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as une excuse pour tout, sauf pour ce désastre de score.', 0, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Même tes excuses ont honte d’être utilisées.', 0, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as pas trouvé le temps. Mais t’as trouvé 8 raisons bidon. Chapeau.', 1, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’es pas responsable… juste victime de ton manque d’effort.', 1, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’aurais pu… si les planètes, ton chat, et ton frigo s’étaient alignés.', 2, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu compiles les excuses comme un collectionneur de défaites.', 2, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('« C’est pas le bon moment. » T’as dit ça en 2021 aussi, non ?', 3, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as pas échoué, tu t’es juste « préservé ». De la réussite.', 3, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu justifies, tu détournes, tu t’expliques. Et tu fais rien.', 4, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as un doctorat en esquive de responsabilité.', 4, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu fais des efforts. Enfin, pour formuler des excuses crédibles.', 5, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('À ce stade, t’as rationalisé ton inaction. Bravo, t’es stable dans l’échec.', 5, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as encore quelques excuses en stock, mais t’as commencé à les ignorer.', 6, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('C’est pas parfait, mais au moins t’arrêtes de te mentir. À moitié.', 6, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu sais que t’es responsable. Et ça te fout un peu les boules. Normal.', 7, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as rangé les excuses dans un tiroir. Elles crient, mais tu tiens bon.', 7, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’agis, tu assumes. Les excuses ont pris leur retraite anticipée.', 8, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Quand t’échoues, tu dis « c’est moi ». Et c’est classe, en fait.', 8, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Plus d’excuses, plus d’auto-sabotage. Juste toi, en version efficace.', 9, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu inspires les autres à arrêter de geindre. Enfin presque.', 9, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu n’as plus besoin d’excuses. Tu fais. Et t’assumes. Comme un boss.', 10, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('On a contacté l’ONU pour t’étudier. T’es l’antidote aux excuses.', 10, 2);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as bouffé tes émotions. Et leurs émotions aussi.', 0, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Ton estomac t’a supplié d’arrêter. Tu lui as répondu avec du sucre.', 0, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Ton frigo te regarde avec peur. Il sait qu’il va y passer.', 1, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’appelles ça du réconfort. Moi j’appelle ça une attaque digestive.', 1, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu dis que t’as faim. Mais t’as juste une mauvaise journée et des chips.', 2, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu mastiques tes problèmes. Et ça fait pas moins de problèmes.', 2, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as hésité entre cuisiner et commander. Tu t’es contenté de grignoter.', 3, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Ton alimentation est une roulette russe en barres chocolatées.', 3, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as pas fait n’importe quoi… mais c’est loin d’être glorieux.', 4, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu nourris ton corps… comme on nourrit un feu de camp : sans réfléchir.', 4, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Pas catastrophique. Pas sain non plus. Tu vis sur un équilibre gras.', 5, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Ton assiette reflète ton ratio : tiède et flou.', 5, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as mangé des légumes… sans pleurer. C’est déjà une victoire.', 6, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu fais des choix. Des fois même des bons. Faut célébrer ça.', 6, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’écoutes ton corps. Il dit pas « pizza » à chaque fois maintenant.', 7, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Ton rapport à la bouffe est moins toxique que ton historique de navigation.', 7, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu manges, tu savoures, tu vis. Et ton ventre t’applaudit.', 8, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('C’est plus un combat. C’est un partenariat gustatif.', 8, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as transformé tes fringales en art. Chapeau chef.', 9, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Ton assiette devrait avoir son propre compte Insta.', 9, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu nourris ton corps comme si c’était un temple. Et il te le rend bien.', 10, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’es la fusion parfaite entre un moine zen et un diététicien étoilé.', 10, 3);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as mis la barre si bas que t’as trébuché dessus.', 0, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Même un échec aurait fait mieux que ce non-sens.', 0, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’approches la réussite… à reculons, en boitant.', 1, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as raté un truc que personne ne rate. C’est un talent rare.', 1, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as tenté. Mal. Mais tenté quand même. Enfin je crois.', 2, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Si t’étais payé à l’échec, t’aurais une villa en Espagne.', 2, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Des efforts flous. Des résultats douteux. Classique.', 3, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as gratté à la porte du succès. Mais t’as pas osé entrer.', 3, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu rates avec style. Presque admirable.', 4, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’approches du « presque » de la réussite. Suspense.', 4, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu stagnes. Mais proprement.', 5, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as pas perdu. T’as juste… pas gagné. Nuance.', 5, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as décroché une micro-réussite. Elle tremble, mais elle existe.', 6, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Petit pas pour toi, mais énorme pas hors de l’échec chronique.', 6, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('On dirait une victoire. C’est petit, mais c’est beau.', 7, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu réussis, à ta façon. Et c’est presque inspirant.', 7, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu gagnes en silence. T’es la version calme du succès.', 8, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as trouvé ton rythme de croisière vers le haut. Continue.', 8, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’es en haut. Tu sais pas trop comment, mais t’y es.', 9, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Tu fais des jaloux. Et tu t’en rends même pas compte.', 9, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('T’as pulvérisé la réussite. Elle te doit des explications.', 10, 4);
INSERT INTO coach_custom (message, ratio, custom) VALUES ('Si le succès était une personne, il te demanderait des conseils.', 10, 4);