USE `trash-userdb`;

INSERT INTO coach (message, ratio) VALUES ('T''es sûr que t''as pas confondu journal de bord et avis de décès ?', 0);
INSERT INTO coach (message, ratio) VALUES ('T''es un danger émotionnel pour toi-même. Et peut-être pour les plantes autour aussi.', 0);
INSERT INTO coach (message, ratio) VALUES ('Je savais que j''allais devoir sortir les sacs mortuaires dès le début.', 0);
INSERT INTO coach (message, ratio) VALUES ('Ton ratio est bas. Comme ton estime. Et probablement ton moral. J''me trompe ?', 0);
INSERT INTO coach (message, ratio) VALUES ('J''espère que t''as pas mis de l''espoir là-dedans, c''était gênant.', 0);
INSERT INTO coach (message, ratio) VALUES ('Si la négativité était un sport, t''aurais déjà une médaille d''or... plutôt en plomb.', 1);
INSERT INTO coach (message, ratio) VALUES ('Si t''étais un plat, t''aurais le goût de regrets et d''humidité.', 1);
INSERT INTO coach (message, ratio) VALUES ('Même une playlist de rupture trouve ça un peu excessif.', 1);
INSERT INTO coach (message, ratio) VALUES ('On est sur du ressenti moisi, là. Limite toxique.', 1);
INSERT INTO coach (message, ratio) VALUES ('Si ton humeur était une couleur, ce serait "Gastro du lundi matin".', 1);
INSERT INTO coach (message, ratio) VALUES ('Wow. Même ton ombre à l''air déprimée. Tu veux qu''on appelle quelqu''un ?', 2);
INSERT INTO coach (message, ratio) VALUES ('À ce stade, même ton miroir hésite à te regarder.', 2);
INSERT INTO coach (message, ratio) VALUES ('T''as pas touché le fond, tu l''as redécoré.', 2);
INSERT INTO coach (message, ratio) VALUES ('Ton énergie dégage un petit goût de défaite tiède.', 2);
INSERT INTO coach (message, ratio) VALUES ('On dirait un lundi permanent dans ton cerveau.', 2);
INSERT INTO coach (message, ratio) VALUES ('T''es pas encore au fond... mais t''as déjà commencé à creuser.', 3);
INSERT INTO coach (message, ratio) VALUES ('La météo intérieure annonce : gris foncé avec un risque d''effondrement.', 3);
INSERT INTO coach (message, ratio) VALUES ('Tu flottes entre le "meh" et le "bof". Solide zone morte.', 3);
INSERT INTO coach (message, ratio) VALUES ('Ton mood a essayé de décoller. Puis il s''est rappelé que c''était toi.', 3);
INSERT INTO coach (message, ratio) VALUES ('On dirait que t''as hésité entre "pas bien" et "pire".', 3);
INSERT INTO coach (message, ratio) VALUES ('T''as connu mieux. Nous aussi, on espérait plus de toi.', 4);
INSERT INTO coach (message, ratio) VALUES ('On sent l''effort... très loin, mais on le sent.', 4);
INSERT INTO coach (message, ratio) VALUES ('C''est pas le fond, mais c''est clairement pas la surface non plus.', 4);
INSERT INTO coach (message, ratio) VALUES ('T''es sur une pente douce... vers le néant.', 4);
INSERT INTO coach (message, ratio) VALUES ('Ta vibe est molle. Littéralement. On pourrait s''asseoir dessus.', 4);
INSERT INTO coach (message, ratio) VALUES ('Bof. Ni chaud ni froid. T''existes, on va dire.', 5);
INSERT INTO coach (message, ratio) VALUES ('Tu vis, tu respires. C''est déjà ça, j''imagine.', 5);
INSERT INTO coach (message, ratio) VALUES ('Statistiquement, t''es là. Emotionnellement, on sait pas trop.', 5);
INSERT INTO coach (message, ratio) VALUES ('Statut: en vie, techniquement. Emotionnellement... joker.', 5);
INSERT INTO coach (message, ratio) VALUES ('T''as la vibe d''un ascenseur bloqué entre deux étages.', 5);
INSERT INTO coach (message, ratio) VALUES ('Bon, c''est pas incroyable... mais au moins t''as pas envie de frapper ton reflet.', 6);
INSERT INTO coach (message, ratio) VALUES ('Tu fais de ton mieux. Et franchement, c''est moins pire que d''habitude.', 6);
INSERT INTO coach (message, ratio) VALUES ('Une vibe tiède, comme une pizza micro-ondes à moitié cuite.', 6);
INSERT INTO coach (message, ratio) VALUES ('Y''a un soupçon de lumière. Très léger. Presque suspect.', 6);
INSERT INTO coach (message, ratio) VALUES ('Pas mal. Enfin, pour quelqu''un qui part de loin.', 6);
INSERT INTO coach (message, ratio) VALUES ('On dirait que t''as pas tout foiré aujourd''hui. Félicitations, presque.', 7);
INSERT INTO coach (message, ratio) VALUES ('Regarde-toi, presque stable. Tu vas finir par croire en toi, non ?', 7);
INSERT INTO coach (message, ratio) VALUES ('T''as évité la crise existentielle aujourd''hui. Petit exploit.', 7);
INSERT INTO coach (message, ratio) VALUES ('T''approches du bonheur. Mais reste concentré, ça pourrait te surprendre.', 7);
INSERT INTO coach (message, ratio) VALUES ('Fais gaffe, à ce rythme t''es à deux bonnes nouvelles de sourire pour de vrai.', 7);
INSERT INTO coach (message, ratio) VALUES ('Regarde-toi, à deux doigts d''être une pub pour la joie de vivre.', 8);
INSERT INTO coach (message, ratio) VALUES ('C''est presque louche, cette bonne humeur. T''as gagné au loto ou quoi ?', 8);
INSERT INTO coach (message, ratio) VALUES ('T''es pas encore une source d''inspiration, mais t''as arrêté d''être une alerte rouge.', 8);
INSERT INTO coach (message, ratio) VALUES ('Là t''as une ambiance "presque inspirant". Presque.', 8);
INSERT INTO coach (message, ratio) VALUES ('Ta bonne humeur commence à me fatiguer. Garde ça pour toi.', 8);
INSERT INTO coach (message, ratio) VALUES ('Wow, calme-toi Bouddha, tu vas finir par inspirer les autres.', 9);
INSERT INTO coach (message, ratio) VALUES ('T''éblouis le néant. C''est presque poétique.', 9);
INSERT INTO coach (message, ratio) VALUES ('T''as dû marcher sur un arc-en-ciel ce matin.', 9);
INSERT INTO coach (message, ratio) VALUES ('Arrête de rayonner comme ça. On va te taxer de gourou.', 9);
INSERT INTO coach (message, ratio) VALUES ('T''as bu quoi ce matin ? Du jus de licorne en promo ?', 9);
INSERT INTO coach (message, ratio) VALUES ('T''as volé la lumière du soleil ou quoi ? T''es insupportablement positif.', 10);
INSERT INTO coach (message, ratio) VALUES ('Tu viens de battre un record de bonheur. Le tien. Et ça me fatigue.', 10);
INSERT INTO coach (message, ratio) VALUES ('Si tu souris plus fort, tu vas t''envoler. Ou énerver tout le monde.', 10);
INSERT INTO coach (message, ratio) VALUES ('T''as un glow de divinité, c''est insupportable. Bravo.', 10);
INSERT INTO coach (message, ratio) VALUES ('Sérieusement, c''est encore légal d''être aussi bien ?', 10);
INSERT INTO coach (message, ratio) VALUES ('J''ai montré ton état mentale à un psy. Il a fermé boutique.', 20);
INSERT INTO coach (message, ratio) VALUES ('Je crois en toi. Même si tout indique que j''ai tort.', 20);
INSERT INTO coach (message, ratio) VALUES ('C’est bien… continue comme ça. Je prends des notes.', 20);
INSERT INTO coach (message, ratio) VALUES ('Ta vibe donne envie de prendre une douche. De l''intérieur.', 21);
INSERT INTO coach (message, ratio) VALUES ('Tout le monde travese des tunnels. Le tien a juste... des rats.', 21);
INSERT INTO coach (message, ratio) VALUES ('T’inquiète, ça peut toujours être pire. Et ça va l’être.', 21);
INSERT INTO coach (message, ratio) VALUES ('T''es pas bas, t''es à un niveau secret de souffrance.', 22);
INSERT INTO coach (message, ratio) VALUES ('Un jour, cette journée sera un souvenir. Comme les jeans baggy.', 22);
INSERT INTO coach (message, ratio) VALUES ('C’est pas la fin du monde. Juste la tienne, probablement.', 22);
INSERT INTO coach (message, ratio) VALUES ('Tu traînes dans le néant. Avec une pancarte "Faites pas attention".', 23);
INSERT INTO coach (message, ratio) VALUES ('Tu frôles quelque chose. C''est pas la lumière, mais c''est pas mal.', 23);
INSERT INTO coach (message, ratio) VALUES ('On observe. On juge pas. Enfin… pas encore.', 23);
INSERT INTO coach (message, ratio) VALUES ('Tu a le charisme d''un PowerPoint oublié.', 24);
INSERT INTO coach (message, ratio) VALUES ('Il faut bien des jours moyens pour apprécier les bons. T''en fais don au monde.', 24);
INSERT INTO coach (message, ratio) VALUES ('C’est un choix de mood, ça. Intéressant. Très… révélateur.', 24);
INSERT INTO coach (message, ratio) VALUES ('T’es la page blanche de l’émotion. Même les robots font mieux.', 25);
INSERT INTO coach (message, ratio) VALUES ('T’es en équilibre. C’est fragile. Et beau, d’une certaine façon.', 25);
INSERT INTO coach (message, ratio) VALUES ('Tu flottes dans la norme. C’est parfait pour qu’on t’oublie.', 25);
INSERT INTO coach (message, ratio) VALUES ('T''as mis un pied dans le positif... et tu l''as retiré par réflexe.', 26);
INSERT INTO coach (message, ratio) VALUES ('Y''a de la lumière dans ce que tu ressens. Laisse-la sortir un peu.', 26);
INSERT INTO coach (message, ratio) VALUES ('C’est mignon cette petite stabilité. On verra combien de temps ça tient.', 26);
INSERT INTO coach (message, ratio) VALUES ('Tu surfes sur une vague de “ça ira”... mais sans planche.', 27);
INSERT INTO coach (message, ratio) VALUES ('Tu deviens quelqu’un de stable. Ou un meuble. Dans tous les cas, bravo.', 27);
INSERT INTO coach (message, ratio) VALUES ('Oh. Du progrès. Ça rendra la chute encore plus drôle.', 27);
INSERT INTO coach (message, ratio) VALUES ('T’as l’air heureux. C’est sûrement une erreur du système.', 28);
INSERT INTO coach (message, ratio) VALUES ('Tu pourrais inspirer les autres. Ou au moins les faire sourire. Et c’est déjà énorme.', 28);
INSERT INTO coach (message, ratio) VALUES ('Tu sembles heureux. Est-ce que tu sais pourquoi, vraiment ?', 28);
INSERT INTO coach (message, ratio) VALUES ('Trop de bonheur. C’est suspect. Tu caches un truc ?', 29);
INSERT INTO coach (message, ratio) VALUES ('Continue comme ça. Tu fais du bien à l’univers.', 29);
INSERT INTO coach (message, ratio) VALUES ('Fascinant. Ton état dépasse les prévisions. On observe.', 29);
INSERT INTO coach (message, ratio) VALUES ('On a atteint un niveau de lumière qui brûle les yeux. Bravo, ange détestable.', 30);
INSERT INTO coach (message, ratio) VALUES ('T’es une anomalie positive. Un miracle statistique. Et j’adore ça.', 30);
INSERT INTO coach (message, ratio) VALUES ('T’es trop bien. Beaucoup trop. Le système va devoir s’ajuster.', 30);