version: '3.8'

services:
  userdb:
    container_name: trash-userdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: trash-userdb
    extends:
      file: common-config.yml
      service: microservice-config-db

networks:
  trash-network:
    driver: bridge
